import { escapeInvoiceHtml as e, invoiceMoney as usd, type InvoiceFinancials, type PaymentHistory } from './payment-history.ts';

/** A read-only companion to the GHL invoice; GHL remains the ledger. */
export function invoiceStatement(invoice: InvoiceFinancials, history: PaymentHistory, projectCode: string): string {
  const value=(n:number|null)=>n===null?'Not supplied by GHL':usd(n);
  const totals=[['Subtotal',value(invoice.subtotal)],['Discount',value(invoice.discount)],['Tax',value(invoice.tax)],['Invoice total',usd(invoice.total)],['Paid on this invoice',usd(invoice.paid)],['Amount due on this invoice',usd(invoice.due)]];
  const logo=/^https:\/\//i.test(invoice.business.logo)?`<img src="${e(invoice.business.logo)}" alt="${e(invoice.business.name)} logo">`:'';
  // Terms HTML is isolated without scripts, forms, navigation or same-origin privileges.
  const terms=invoice.terms?`<h2>Notes &amp; terms from GoHighLevel</h2><iframe title="Invoice notes and terms" sandbox referrerpolicy="no-referrer" srcdoc="${e('<meta http-equiv="Content-Security-Policy" content="default-src \'none\'; style-src \'unsafe-inline\'"><style>body{font:14px/1.6 Arial;overflow-wrap:anywhere}</style>'+invoice.terms)}"></iframe>`:'';
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Invoice ${e(invoice.number)} - ${e(projectCode)}</title><style>
  *{box-sizing:border-box;letter-spacing:0}body{margin:0;background:#edf1f3;color:#18232c;font:15px/1.5 Arial,sans-serif}.bar{background:#17242e;color:white;padding:14px 24px;display:flex;justify-content:space-between;gap:16px;flex-wrap:wrap}.bar a{color:white}.sheet{max-width:920px;background:white;margin:28px auto;padding:40px}header{display:flex;justify-content:space-between;gap:24px;border-bottom:2px solid #263c48;padding-bottom:24px}header img{max-width:210px;max-height:80px;object-fit:contain}h1{font-size:28px;margin:0}h2{font-size:16px;margin:30px 0 12px}.address{white-space:pre-line}.muted{color:#596873;font-size:13px}.meta{display:flex;justify-content:space-between;gap:20px;margin:24px 0;flex-wrap:wrap}table{width:100%;border-collapse:collapse}th,td{padding:12px 8px;border-bottom:1px solid #dce2e7;text-align:left;vertical-align:top;overflow-wrap:anywhere}th{font-size:12px;color:#536370}td.num,th.num{text-align:right;font-variant-numeric:tabular-nums}.totals{max-width:430px;margin:22px 0 22px auto}.totals div{display:flex;justify-content:space-between;gap:20px;padding:8px 0}.totals div:last-child{border-top:2px solid #263c48;font-size:18px;font-weight:bold}.history{overflow-x:auto}.notice{border-left:3px solid #0b806c;padding:12px 16px;background:#eff9f6;margin:16px 0}iframe{border:1px solid #dce2e7;width:100%;height:260px}.business{overflow-wrap:anywhere}header>div{min-width:0} @media(max-width:640px){.sheet{padding:20px;margin:0}header{flex-direction:column}h1{font-size:24px}th,td{padding:8px 4px;font-size:12px}.history table{min-width:480px}}@media print{body{background:white}.bar{display:none}.sheet{margin:0;padding:12px;max-width:none}header, .totals{break-inside:avoid}}
  </style></head><body><nav class="bar"><a href="/dashboard/invoices">Back to invoices</a><span>Read-only invoice summary / ${e(invoice.status)}</span></nav><main class="sheet"><header><div class="business">${logo}<strong style="display:block">${e(invoice.business.name)}</strong><div class="address">${e(invoice.business.address)}</div><div>${e(invoice.business.phone)}</div><div>${e(invoice.business.website)}</div></div><div><h1>INVOICE SUMMARY</h1><div>${e(invoice.number)}</div><div>${e(projectCode)}</div></div></header><section class="meta"><div><strong>Bill to</strong><div>${e(invoice.customer)}</div></div><div>Issued: ${e(invoice.issueDate)}<br>Due: ${e(invoice.dueDate)}</div></section><table><thead><tr><th>Description</th><th class="num">Quantity</th><th class="num">Unit price</th></tr></thead><tbody>${invoice.items.map(item=>`<tr><td>${e(item.name)}<div class="muted">${e(item.description)}</div></td><td class="num">${item.quantity}</td><td class="num">${usd(item.amount)}</td></tr>`).join('')}</tbody></table><div class="totals">${totals.map(([label,amount])=>`<div><span>${label}</span><span>${amount}</span></div>`).join('')}</div><h2>Other project invoices</h2><p class="muted">GHL records checked ${e(history.checkedAt)}. Only invoices explicitly linked to this project are included.</p><div class="history"><table><thead><tr><th>Invoice</th><th>Status</th><th class="num">Total</th><th class="num">Received</th><th class="num">Outstanding</th></tr></thead><tbody>${history.entries.map(row=>`<tr><td>${e(row.number)}</td><td>${e(row.status)}</td><td class="num">${usd(row.total)}</td><td class="num">${usd(row.paid)}</td><td class="num">${usd(row.due)}</td></tr>`).join('')||'<tr><td colspan="5">No other issued invoices linked to this project.</td></tr>'}</tbody></table></div><div class="notice">Received on other linked invoices: <strong>${usd(history.paid)}</strong><br>Previous installment payments are not deducted again from this invoice. Unrecorded or unlinked payments are excluded.</div>${terms}<p class="muted">This summary does not send an invoice or record a payment. GoHighLevel holds the authoritative invoice and payment records. Missing tax or subtotal data is not treated as zero.</p></main></body></html>`;
}
